### ISSUE TITLE
Support HeaderView/ FooterView for Sections

### ISSUE THREAD

**Issue by faris-mobile89** [GenericDataSource/GenericDataSource#11]
How to add footer or header view for each section.

in Objective C we can use:
`- (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section {}
`

**Comment by mohamede1945** [comment]
You create a class conforming to `SupplementaryViewCreator` or use any of its implementation like `BasicSupplementaryViewCreator`.

Then you assign it to the data source with any of the following methods

```swift
/// Sets a header creator.
open func set(headerCreator: SupplementaryViewCreator)

/// Sets a footer creator.
open func set(footerCreator: SupplementaryViewCreator)

/// Sets both header and footer creators.
open func set(headerCreator: SupplementaryViewCreator, footerCreator: SupplementaryViewCreator) 
```

If you have a one basic data source. Just assign it to it. But if you have a `CompositeDataSource`, you can assign it to the root composite data source to get the same headers and footer for all sections or assign different ones to**ALL** the children to get different headers and/or footers for each section.

**Comment by mohamede1945** [comment]
Please re-open if that didn't help.
