### ISSUE TITLE
Spacing between cells

### ISSUE THREAD

**Issue by kennyDang** [GenericDataSource/GenericDataSource#14]
How would we accomplish this?

**Comment by mohamede1945** [comment]
You mean [minimumlinespacing](https://developer.apple.com/documentation/uikit/uicollectionviewflowlayout/1617717-minimumlinespacing) & [minimuminteritemspacing](https://developer.apple.com/documentation/uikit/uicollectionviewflowlayout/1617706-minimuminteritemspacing)?

**Comment by kennyDang** [comment]
Oh, so I would also use this to space out each data source in a table view list?

**Comment by kennyDang** [comment]
Thanks for the comments. I decided to just add an empty view inside of each cell. From there, it's easy enough to adjust the height to give the appearance of space :)
